server {
    listen 80;
    listen [::]:80;
    server_name www.n8n.mkluckoff.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://n8n.mkluckoff.ru$request_uri;
    }
}
